### ISSUE TITLE
Problem with axia module and alsa

### ISSUE THREAD

**Issue by jeremiel26** [radiorabe/systemd-axia-alsa#2]
Hi, i don't think it's a problem with your package, but we have a problem:

if i record only 1 stereo channel, the sound is ok... sometimes it cracks a little bit, but it's ok
But if i record more channels (audacity, alsa, 8 input, no jackd but the same append with jackd), the sound is recorded very fast, like the sample rate or something else was wrong.

do you know how to fix that?

Maybe something to add in /etc/asound.conf or /etc/modprobe.d/alsa-base.conf
or somthing else?

regards
[Piste audio.zip](https://github.com/radiorabe/systemd-axia-alsa/files/3300795/Piste.audio.zip)

**Comment by paraenggu** [comment]
Hi @jeremielorente, this sounds similar to a [problem I encountered a while ago, with the combination of AXIA - ALSA Soundcard Driver for Livewire and Jackd](http://lists.jackaudio.org/pipermail/jack-devel-jackaudio.org/2018-January/001256.html). The [solution](http://lists.jackaudio.org/pipermail/jack-devel-jackaudio.org/2018-January/001295.html) back then was to instruct Jackd to explicitly use only the first two channels instead of starting it with the default behavior, where it tries to bind to all 8 available channels.

I would check the following:
Make sure you have configured all required sources within `/etc/axia/lwr.conf` (and disable unused sources)

Verify if the Livewire+ sources are available as alsa capture devices and working correctly, by trying to record from the first capture device of your configured Livewire+ Alsa device with `arecord`. Use two channels and make sure to use the correct rate and format:
```bash
arecord -D hw:0 -c 2 -d 10 -r 48000 -f S32_LE -v /tmp/test-arecord.wav`
```
* Iterate over all devices (`-D [...]`) you have configured
* Do the same but this time with 8 channels (`-c 8`) to see if the chipmunks are paying you a visit.

If Alsa recording is working properly, you could proceed with Audacity, by checking that Audacity only tries to bind to the first two channels of the actual configured devices and doesn't tries to bind to some unconfigured but available channels/devices.

As a last step, contact the [Paravel support](https://www.paravelsystems.com/support).

For the audio cracking problems, I would increase the buffer or period sizes and play with the real-time related settings of your recording processes or audio servers.

**Comment by jeremiel26** [comment]
Thank you for your quick answer. :) i've already seen your past messages but i can't limit my use with 2 channels

This is my lwr.conf file:

```
SET IPCLK_ADDR:"239.192.255.2" NIC_IPADDR:"192.168.101.2"
SRC 1 RTPE:1 RTPA:"239.192.48.13" PSNM:"Rivendell"
DST 1 NAME:"PigeFM" ADDR:"239.192.44.42"
DST 2 NAME:"PigePCM" ADDR:"239.192.44.37"
```
after reboot, these are the result for these test:
```
arecord -D hw:1 -c 2 -d 10 -r 48000 -f S32_LE -v /home/rd/Pige/test.wav
arecord -D hw:1,0 -c 2 -d 10 -r 48000 -f S32_LE -v /home/rd/Pige/test0.wav
arecord -D hw:1,1 -c 2 -d 10 -r 48000 -f S32_LE -v /home/rd/Pige/test1.wav
arecord -D hw:1 -c 4 -d 10 -r 48000 -f S32_LE -v /home/rd/Pige/testc4.wav

```
on testc4.wav, chipmunks are back...

jackd works great with 2in/2out but if i setup 4in/4out or 8in/8out, chipmunks are back!

I've already try to email Fred from paravel, but he reply "when he want"... i try to make it work since one year and he stop answer for monthssss... that's why i try to get answer here, i've very disappointed with Paravel support. I was the one to warn him that centos kernel was no longer able to compile axia module and that's why he add a paravel kernel variant.
Ok, it works with 2 channels... but we've pay for 8 channels and need 8 channels for our configuration... 

Thanks again for your help! :)

is anyone ever been able to get this driver works properly with 8 channels???

[test.zip](https://github.com/radiorabe/systemd-axia-alsa/files/3315702/test.zip)

**Comment by paraenggu** [comment]
Just to make sure, that I understand you correctly: You would like to record from the following two Livewire+ destinations:
```
DST 1 NAME:"PigeFM" ADDR:"239.192.44.42"
DST 2 NAME:"PigePCM" ADDR:"239.192.44.37"
```

If yes, aren't those simple stereo streams or are they really using more than two channels (surround)?

In case these are stereo streams (2 channels), everything seems to work on your side (except for the annoying unused channel behavior). 

You will have to record from the first two (and only the first two) channels of the `hw:1,0` and `hw:1,1` Alsa capture devices, rather than trying to access more channels on `hw:1` (which is the same as `hw:1,0` IIRC).
If you're going to configure additional Livewire+ destinations within your `lwr.conf` you will have to address them as `hw:1,2` and `hw:1,3`. Which will result in a total of 8 channels then:

```
DST 1 NAME:"PigeFM" ADDR:"239.192.44.42"
   |
   +--- hw:1,0
          +--- Channel 1 => Capture channel 1
          +--- Channel 2 => Capture channel 2

DST 2 NAME:"PigePCM" ADDR:"239.192.44.37"
   |
   +--- hw:1,1
          +--- Channel 1 => Capture channel 3
          +--- Channel 2 => Capture channel 4

DST 3 NAME:"Example-DST-3" ADDR:"239.192.44.XX")
   |
   +--- hw:1,2
          +--- Channel 1 => Capture channel 5
          +--- Channel 2 => Capture channel 6

DST 4 NAME:"Example-DST-4" ADDR:"239.192.44.XX")
   |
   +--- hw:1,3
          +--- Channel 1 => Capture channel 7
          +--- Channel 2 => Capture channel 8
```

I don't know if this is directly possible with Audacity, you would probably have to go over Jackd first.

> i've very disappointed with Paravel support

I know your pain, I've spent months helping to debug some problems with "standard" vs. "Livestream" settings and the Axia driver. As I finally was able to easily reproduce the whole problem, it was decided to forward my mails to `/dev/null`...

**Comment by jeremiel26** [comment]
i don't use livewire as surround but exactly like you've write it in your lwr.conf sample file: stereo inputs.
I've only use audacity to trie, but i'll not use it in production.
I'll use jackd and use rotter to record fm tuner, an other rotter record from main to export podcast, liquidsoap to send audio to icecast etc etc

with this configuration, i have the same problems on records: chipmunks voices!

i've already make this kind of use (jackd, rotter, liquidsoap, stereotool etc) without problem with usb multi in/out sound card (behringer x18, edirol fa101 etc)

**Comment by paraenggu** [comment]
Please post your jackd startup options with the above configuration.

**Comment by jeremiel26** [comment]
I'll try to use jackd after making it work on alsa... I've send a mail to Fred (again) asking him to solve this problem or refund us...

**Comment by jeremiel26** [comment]
Hi,
At last... Fred answered! Hope this will help...

In fact, Paravel module can't be used as a "normal" sound card with multiple in/out. Each stereo in/out have to be viewed as an interface...

So "hw:Axia,0" is the first card,  "hw:Axia,1" is the second one, "hw:Axia,2" is the third... etc etc

As jack can only connect to one interface, that's why we have to limit in/out to 2 channels only or we get our "chipmunks" problem...

Fred adviced me to use Rivendell in order to use 3 "cards" thru Alsa and, if needed, jackd to connect to the fourth one...

It works... No more chipmunks ;) But that's not the way i'd like to use my server...

I've asked him if the merge capabilities of Alsa could be a way to go for me... Fred advise me to forget it, because of problems of sync, glitches etc... These recommandations are mentionned too on jack project page and Alsa documentation.
But as we use the same hardware (not merging intel hda with usb sound card for exemple), i've give a try...

**And it works very well!** just have 4 xrun at start, but it's running very well, with great sound quality for more than 6 hours now, with 4 channels (2 stereo in/out), connected to 2 rotter instance and butt streaming to icecast server!

So how to make it works?

This is my ~/.asoundrc file (based on https://alsa-project.org/wiki/Asoundrc sample):

```
pcm.multi {
	type multi;
        slaves.a.pcm "hw:1,0";
        slaves.a.channels 2;
        slaves.b.pcm "hw:1,1";
        slaves.b.channels 2;
        bindings.0.slave a;
        bindings.0.channel 0;
        bindings.1.slave a;
        bindings.1.channel 1;
        bindings.2.slave b;
        bindings.2.channel 0;
        bindings.3.slave b;
        bindings.3.channel 1;
}
ctl.multi {
	type hw;
        card 2;
}
pcm.ttable {
	type route;
        slave.pcm "multi";
        slave.channels 4;
        ttable.0.0 1;
        ttable.1.1 1;
        ttable.2.2 1;
        ttable.3.3 1;
}
ctl.ttable {
	type hw;
        card 2;
}
```

After that, start jack with "ttable" interface (i've written it on qjackctl as it's not in the list of interfaces...), set channels in/out (4/4 in my case), save and... start!

Hope this help you too!

**Comment by paraenggu** [comment]
Thanks for sharing, I'm going to close this issue then.
